import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ErrorAlert from "@/components/Alert/ErrorAlert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextWrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' px-4 sm:px-12 md:px-24 xl:px-52'}>
        <Navbar/>
        <ErrorAlert/>
        <div className="text-gray-700">
          {children}
        </div>
      </body>
    </html>
  );
}
