import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BaseAlert from "@/components/Alert/BaseAlert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextWrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/next-write-logo.svg" />
      </head>
      <body className={inter.className + ' px-4 sm:px-12 md:px-24 xl:px-52 bg-gray-800 text-white'}>
        <Navbar/>
        <BaseAlert/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
